### ISSUE TITLE
CI build fails with error (misconfiguration)

### ISSUE THREAD

**Issue by richardtop** [AladinWay/TransitionButton#10]
Travis CI build fails with error,
the reason for it is not in erroneous library code, but due to misconfiguration.

For some reason, `TransitionButton.framework` is not being copied. On my local machine I've fixed this error by building library code with Carthage and manually importing the framework.

**Comment by AladinWay** [comment]
I know, it's really annoying, I will try to fix that and push a fix as soon as possible.  Thank you for reporting :)

**Comment by AladinWay** [comment]
@richardtop it's fixed now :)
