### ISSUE TITLE
Spinner not showing

### ISSUE THREAD

**Issue by Shekhar175** [AladinWay/TransitionButton#11]
When creating Button object I have given the frame .zero after that I am adding constraints programatically, In that case spinner is not showing. If I create Button with some frame then Spinner is visible but as per frame given not as per updated constraints

**Comment by azhararmar** [comment]
I've got the same issue.

**Comment by gemini2100** [comment]
I guess you use autolayout, This fixing can show the spinner but not best way . 
class TransitionButton, remove set 'spinnerColor' code
`private func setup() {
        self.clipsToBounds  = true
        //spiner.spinnerColor = spinnerColor  //remove this line
    }`
and please delete var spinnerColor
` //@IBInspectable open var spinnerColor: UIColor = UIColor.white {
    //    didSet {
    //        spiner.spinnerColor = spinnerColor
     //   }
    //}`
All of these for init var spiner after TransitionButton resize by autolayout.

**Comment by AladinWay** [comment]
Thank you for reporting the issue. I will investigate the issue as soon as possible and apply a fix if needed.

**Comment by AladinWay** [comment]
It should be fixed in v0.4.0. Feel free to open the issue if you still have a problem.
