### ISSUE TITLE
StartAnimation Crash in swift 4

### ISSUE THREAD

**Issue by Rjmaurya13** [AladinWay/TransitionButton#14]
App is crashing is swift 4. Due to spinner colour.

**Comment by AladinWay** [comment]
@Rjmaurya13  Thank you for reporting. Can you please provide more details. The crash log and how to reproduce it ? :)

**Comment by AladinWay** [comment]
Unfortunately I can't reproduce it in the example project. I will close this issue for now, feel free to open it if you still have the issue

**Comment by hasanakg** [comment]
Here is the debug info. You can reproduce it with cocoapods installation I think.

`2018-04-20 10:58:16.656164+0300 [14064:6247118] Failed to set (spinnerColor) user defined inspected property on (UIButton): [<UIButton 0x12fd1e980> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key spinnerColor.`

**Comment by hasanakg** [comment]
I solved mine; when you set `Custom Class` you also need to specify `Module` property to `TransitionButton`. 

![Image](https://i.imgur.com/OphZIpf.png)

**Comment by AladinWay** [comment]
Glad you were able to fix the issue. Thank you for using `TransitionButton` :)

**Comment by soareseneves** [comment]
Same error for me, thanks for the solution @hasanakg!!!
