### ISSUE TITLE
The button doesn't fill the full screen size

### ISSUE THREAD

**Issue by volkoivan** [AladinWay/TransitionButton#16]
You can see at the image the size of the button once it finished it's stop animation.

<img width="362" alt="2018-04-02 15 45 56" src="https://user-images.githubusercontent.com/9116618/38193757-1a90b9de-368d-11e8-9a73-83ba434345d8.png">

Here it's original layout:
![2018-04-02 15 47 55](https://user-images.githubusercontent.com/9116618/38193785-445c15ce-368d-11e8-8b81-05d1a548883c.png)

Is it me doing something wrong, or is it the problem with the library?

**Comment by AladinWay** [comment]
Thank you for reporting the issue. Can you reproduce it in the example project ? which device/simulator did you use for testing ?

**Comment by volkoivan** [comment]
Simulator iPhone8 Plus
To reproduce it remove the leading constraint of the button so it becomes a circle
Then you'll notice a gap on the left top corner after stopLoading call

**Comment by AladinWay** [comment]
@megavirus74  in file `TransitionButton.swift` line 190 you can increase the expand value: 
`expandAnim.toValue  = 26.0`
Maybe It should be an optional property when choosing expand animation or a button property. I will think about that and update the library if needed. Note that usually while expanding you will have a fade animation of the next screen, so it should not be a problem if the button does not expand fully, but that depends of the user needs, I may update add it as property. Thank you for reporting and using the library.

**Comment by volkoivan** [comment]
I'm using it as a pod, so changing it in code will be a little messy, but okay if there is no workaround for now
Maybe make it based on the button position and size compared to view size?
Anyway, thanks for help!

**Comment by AladinWay** [comment]
I will update it tonight ;)

**Comment by AladinWay** [comment]
@megavirus74 It's fixed now, sorry for the delay. It will be included in the next release.
