### ISSUE TITLE
Execute completion block after .normal and .shake animations have completed

### ISSUE THREAD

**Issue by dachev** [AladinWay/TransitionButton#18]
stopAnimation's `completion` block is executed before `.normal` and `.shake` animations have completed

**Comment by AladinWay** [comment]
Thank you for reporting, I have fixed it and it should including in the next release

**Comment by dachev** [comment]
@AladinWay Has this been fixed? I don't see any commits or branches referencing this issue.

**Comment by AladinWay** [comment]
@dachev It will be included in the version `0.5.0` that will be released tonight :)

**Comment by dachev** [comment]
@AladinWay Can you please point me to the code commit? I would like to review the diff.

**Comment by AladinWay** [comment]
@dachev I will notify you once I will push the code ;)

**Comment by AladinWay** [comment]
@dachev It's out now :)

**Comment by dachev** [comment]
@AladinWay It works great. Thanks!
