### ISSUE TITLE
Expose init func

### ISSUE THREAD

**Issue by cuzv** [AladinWay/TransitionButton#23]
Here is my situation: After updated to `0.5.0`, My `TransitionButtonSubclass` TransitionButton subclass cannot initialize by using `let button = TransitionButtonSubclass(type: .system)`.

May I suggest you expose the `init(frame: CGRect)` function to make inherited class have the ability to initialize instance just like the version 0.4.0.

**Comment by AladinWay** [comment]
@cuzv I have exposed the `init(frame:)` method again in version `0.5.1`
