### ISSUE TITLE
Update Podspec for Swift 4.2

### ISSUE THREAD

**Issue by ugenlik** [AladinWay/TransitionButton#27]
for swift 4.2
`pod 'TransitionButton', :git => 'https://github.com/AladinWay/TransitionButton.git'` works 

but just `pod 'TransitionButton'` doesn't work it pulls the last version not the master branch of the repo.

**Comment by AladinWay** [comment]
I have just released the version `0.5.2` so it should be fine now to use just `pod 'TransitionButton' ` make sure to run `pod repo update` first
