### ISSUE TITLE
Warning when compiling

### ISSUE THREAD

**Issue by fidmor89** [AladinWay/TransitionButton#30]
The following warning is displayed after building project:

`Ld /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/TransitionButton/TransitionButton.framework/TransitionButton normal x86_64 (in target: TransitionButton)
    cd /Users/fidel/Source/ios-contractor/ProjectName/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/TransitionButton -F/Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/TransitionButton -filelist /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Pods.build/Debug-iphonesimulator/TransitionButton.build/Objects-normal/x86_64/TransitionButton.LinkFileList -install_name @rpath/TransitionButton.framework/TransitionButton -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/TransitionButton -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Pods.build/Debug-iphonesimulator/TransitionButton.build/Objects-normal/x86_64/TransitionButton_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Pods.build/Debug-iphonesimulator/TransitionButton.build/Objects-normal/x86_64/TransitionButton.swiftmodule -framework UIKit -Wl,-pie -framework Foundation -framework UIKit -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Pods.build/Debug-iphonesimulator/TransitionButton.build/Objects-normal/x86_64/TransitionButton_dependency_info.dat -o /Users/fidel/Library/Developer/Xcode/DerivedData/ProjectName-hebutnrxojkogvajrzazbwqyetri/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/TransitionButton/TransitionButton.framework/TransitionButton
`

`ld: warning: -pie being ignored. It is only used when linking a main executable
`

**Comment by runkaiz** [comment]
Delete your deprived data and try build again.

**Comment by fidmor89** [comment]
Thanks
