### ISSUE TITLE
Could not build Objective-C module 'TransitionButton'

### ISSUE THREAD

**Issue by juntaosh** [AladinWay/TransitionButton#31]
Short description:

Can't build with error 'Objective-C module 'TransitionButton'
with compiler error 7 errors (Swift Compiler Error)
I tried your repo and it worked perfectly and I also tried
https://github.com/ReactiveX/RxSwift/issues/728
 but it also fail to work.

xcode version 10.0.0(10A255)

**Comment by sujewan** [comment]
> pod 'TransitionButton', :git => 'https://github.com/AladinWay/TransitionButton.git'

 works
