### ISSUE TITLE
How to i set animated Button Position to right instead of Center

### ISSUE THREAD

**Issue by nitingohel** [AladinWay/TransitionButton#33]
First thanks for the great code...

I use TransitionButton at right side of Navigation Controller how ever button width bit bigger and on animation time that button become a rounded and take a position of center that looks wired for my UI. I have try a lot for find a way to make animation button position to right for ever but no luck. Can you please help

I have attached a screenshot bellowed:

![img_4467](https://user-images.githubusercontent.com/5137595/50832593-b5476580-1374-11e9-9946-950ba6dfcbe2.jpg)
![img_4466](https://user-images.githubusercontent.com/5137595/50832595-b5dffc00-1374-11e9-8981-a56b041107f4.jpg)

**Comment by AladinWay** [comment]
Sorry for the the late response. Do you still need help ?
