### ISSUE TITLE
Issue with shadowed button

### ISSUE THREAD

**Issue by ismaiI1** [AladinWay/TransitionButton#37]
Hi, I really like to TransitionButton and i used it my previous projects :)  

Now, I want to use it my new project but when I was add shadow to UIButton (TransitionButton) the animation is very laggy as you can see from below.. If I remove shadow, it's perfectly working.. How can I fix this?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8086679/52566147-089c5000-2e1a-11e9-869d-c1047743751c.gif)

**Comment by ghost** [comment]
@invisible66 
TransitionButton doesn't have the cause of that. 
try it:
```
transitionButton.layer.shouldRasterize = true
transitionButton.layer.rasterizationScale = 2.0
```

**Comment by ismaiI1** [comment]
I'll try.. thanks..
