### ISSUE TITLE
[!] Unable to find a specification for `TransitionButton`

### ISSUE THREAD

**Issue by gbergamo** [AladinWay/TransitionButton#4]
I'm getting this error trying to integrate transition button to my project via pod.
I'm using pod 'TransitionButton' there's something wrong?
It's ok in cocoa pods website: https://cocoapods.org/pods/TransitionButton

**Comment by AladinWay** [comment]
Maybe you don't have the the latest pods list updated can you try please : 

1. open terminal.
2. go to your project path.
3. type: `pod repo update`
4. install pod again.

**Comment by XavierLost** [comment]
The lack of Podfile, "No `Podfile' found in the project directory."
1.Use pod init 
2.pod 'TransitionButton'
3.pod install
It doesn't work,Hope you can help me.
