### ISSUE TITLE
demo app crashes

### ISSUE THREAD

**Issue by GINNOV** [AladinWay/TransitionButton#48]
1.  run the project
2. tap on the first button
3. tap on the <- button

the app crashes
on line:  let toView   = transitionContext.view(forKey: .to)!
Fatal error: Unexpectedly found nil while unwrapping an Optional

**Comment by XavierLost** [comment]
secondVC.modalPresentationStyle = .fullScreen

**Comment by jackxliu** [comment]
Where do you implement "secondVC.modalPresentationStyle = .fullScreen" ? Have the same problem right now.

**Comment by AladinWay** [comment]
@XavierLost is right. I will push an update today to include this as part of the `CustomTransitionViewController`
