### ISSUE TITLE
Ambiguous reference to member 'asyncAfter(deadline:qos:flags:execute:)'

### ISSUE THREAD

**Issue by ghost** [AladinWay/TransitionButton#5]
Hi, I added TransitionButton in a project on Xcode 9 beta , when I open the project and run I get the following error in the code: Ambiguous reference to member 'asyncAfter(deadline:qos:flags:execute:)'

**Comment by AladinWay** [comment]
I have created a new project in `Xcode 9 beta 5` and add the library with `Carthage` and it works fine. Please open this issue again if you still need help.
