### ISSUE TITLE
Swift 5 Update

### ISSUE THREAD

**Issue by Mahdimm** [AladinWay/TransitionButton#50]
Hi,
do you have any plan for updating?
thanks for this awesome library

**Comment by SlavcoPetkovski** [comment]
Any update on this? I have a warning in my project.
![Screen Shot 2020-03-26 at 16 15 11](https://user-images.githubusercontent.com/20534421/77663267-2b85b700-6f7d-11ea-87e1-8dad01a83884.png)

**Comment by AladinWay** [comment]
Working on that now. Will push an update today.
