### ISSUE TITLE
Navigation Controller transition

### ISSUE THREAD

**Issue by ghost** [AladinWay/TransitionButton#51]
Hello, the transition animation not working well with Navigation controller ..
tried to present it like this  but not working:

```
                          let storyboard = UIStoryboard(name: "Main", bundle: nil)
 let navController = storyboard.instantiateViewController(withIdentifier: "FinalBuy") 
 as!FinalBuyViewController
                            self.present(navController, animated: true, completion: nil)
```

the effect is now working but the navigation bar is not showing .. any solutions guys ?

**Comment by AladinWay** [comment]
Thanks for using `TransitionButton` project. Can you please provide more context and steps to reproduce the issue ?

**Comment by dadou181295** [comment]
Thanks sir for reply :)

i'm just trying to present the animation with navigation controller its
going like this :

ViewController (A) -> Navigation controller -> View controller (b)

when then expand effect is going to VC (b)

tried a lot of hours.. this is my code ..
i'm doing the expand with the following code in the completion block and
all that is in a UIAlert action with uialert..

   alert.addAction(.init(title: "OK", style: .default, handler: { (action)
*in*
... and then ..

*let* storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: *nil*)

                            *let* mynavigationController = storyBoard.
instantiateViewController(withIdentifier: "FinalBuy") *as*!
UINavigationController

                            *let* vc = mynavigationController.
topViewController *as*! FinalBuyViewController

                            *self*.navigationController?.present(vc,
animated: *true*, completion: *nil*)

**Comment by dadou181295** [comment]
im getting the exception  :

*Terminating app due to uncaught exception 'NSInvalidArgumentException',
reason: 'Application tried to present modally an active controller
<UINavigationController: 0x10d034c00>.'*

**Comment by ghost** [comment]
i'm just trying to present the animation with navigation controller its
going like this :

ViewController (A) -> Navigation controller -> View controller (b)

when then expand effect is going to VC (b)
inside  `   alert.addAction(.init(title: "OK", style: .default, handler: { (action)
*in*
`  sender.stopAnimation(animationStyle: .expand, revertAfterDelay: 3) {
                            
                       
                            let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
                            let mynavigationController = storyBoard.instantiateViewController(withIdentifier: "FinalBuy") as! UINavigationController
                            let vc = mynavigationController.topViewController as! FinalBuyViewController
                            self.navigationController?.present(vc, animated: true, completion: nil)`

**Comment by ghost** [comment]
i get the exception : 
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UINavigationController: 0x10d034c00>.'`

**Comment by AladinWay** [comment]
It seems like it's an issue not related to `TransitionButton`. You are trying to present a ViewController which already active  https://stackoverflow.com/questions/7429014/application-tried-to-present-modally-an-active-controller
