### ISSUE TITLE
TransitionButton Crash when using with XIB

### ISSUE THREAD

**Issue by maclacerda** [AladinWay/TransitionButton#6]
Hello,

First congratulations for the excellent library you created.

I'm having a problem and would like help, I'm using the TransitionButton on an XIB, and the app is crashing with the error below:

Basically I am adding a UIButton and changing its parent class to TransitionButton, I define my @IBOutlet with the type TransitionButton and when I try to access the button.spinnerColor or button.startAnimating () the app crashes with the error:

`
2017-09-22 11: 12: 18,978 Reserve [99333: 22192085] Unknown class _TtC7Reserve16TransitionButton in Interface Builder file.
`

Any idea?

Thanks a lot

**Comment by AladinWay** [comment]
First, thank you for using the library. Actually the demo project is using Interface builder and it works fine. How did you install the library ? and if possible to isolate the issue in an example project then I can take look at it

**Comment by AladinWay** [comment]
@marcoslacerda  Any update regarding the issue.

**Comment by AladinWay** [comment]
closed to inactivity.
